interface Env {
  DB: D1Database;
  CLOUDFLARE_ACCESS_TEAM_DOMAIN: string;
  CLOUDFLARE_ACCESS_AUDIENCE: string;
  AUTH_RATE_LIMITER: RateLimit;
  API_RATE_LIMITER: RateLimit;
  PROOF_RATE_LIMITER: RateLimit;
  SPONSOR_WALLET_SEED?: string;
  OPERATOR_AUTHORITY_SECRET?: string;
  DISCORD_WEBHOOK_URL?: string;
  PUBLIC_MIDNIGHT_NETWORK?: string;
  PUBLIC_SENSOR_REGISTRY_CONTRACT_ADDRESS?: string;
  OPERATIONS_ALERT_LOW_DUST_TRANSACTIONS?: string;
  OPERATIONS_ALERT_SYNC_LAG_BLOCKS?: string;
  OPERATIONS_ALERT_SYNC_UNSYNCED_MINUTES?: string;
  OPERATIONS_ALERT_PROOF_BACKLOG?: string;
  OPERATIONS_ALERT_PROOF_BACKLOG_AGE_MINUTES?: string;
  OPERATIONS_ALERT_SPONSOR_BACKLOG?: string;
  OPERATIONS_ALERT_SPONSOR_BACKLOG_AGE_MINUTES?: string;
  OPERATIONS_ALERT_PROOF_RATE_LIMIT_EVENTS?: string;
  OPERATIONS_ALERT_REMINDER_MINUTES?: string;
}

declare namespace Cloudflare {
  interface Env {
    SPONSOR_WALLET_SEED?: string;
    OPERATOR_AUTHORITY_SECRET?: string;
    DISCORD_WEBHOOK_URL?: string;
  }
}
