/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=../deployment/wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: 675969477d3349fb00f40c54915acb0a)
interface __BaseEnv_Env {
	SPONSOR_STATE: R2Bucket;
	MANAGED_SOURCE_DATA: R2Bucket;
	DB: D1Database;
	PROOF_QUEUE: Queue;
	SPONSOR_QUEUE: Queue;
	MANAGED_SOURCE_QUEUE: Queue;
	AUTH_RATE_LIMITER: RateLimit;
	API_RATE_LIMITER: RateLimit;
	PROOF_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	CLOUDFLARE_ACCESS_TEAM_DOMAIN: "https://morning-unit-c72e.cloudflareaccess.com";
	CLOUDFLARE_ACCESS_AUDIENCE: "1e64d80f43ed648a2e7c0bfb059c737f76f27ab311cb786d84ab793d296460f9";
	OPERATIONS_ALERT_LOW_DUST_TRANSACTIONS: "1";
	OPERATIONS_ALERT_SYNC_LAG_BLOCKS: "250";
	OPERATIONS_ALERT_WALLET_GRACE_MINUTES: "5";
	OPERATIONS_ALERT_PROOF_BACKLOG: "8";
	OPERATIONS_ALERT_PROOF_BACKLOG_AGE_MINUTES: "10";
	OPERATIONS_ALERT_SPONSOR_BACKLOG: "16";
	OPERATIONS_ALERT_SPONSOR_BACKLOG_AGE_MINUTES: "10";
	OPERATIONS_ALERT_PROOF_RATE_LIMIT_EVENTS: "5";
	OPERATIONS_ALERT_REMINDER_MINUTES: "60";
	PUBLIC_MIDNIGHT_NETWORK: string;
	PUBLIC_SENSOR_REGISTRY_CONTRACT_ADDRESS: string;
	PROOF_SERVER: DurableObjectNamespace<import("./index").ProofServerContainer>;
	SPONSOR_WALLET: DurableObjectNamespace<import("./index").ServerWalletContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ProofServerContainer" | "ServerWalletContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCESS_TEAM_DOMAIN" | "CLOUDFLARE_ACCESS_AUDIENCE" | "OPERATIONS_ALERT_LOW_DUST_TRANSACTIONS" | "OPERATIONS_ALERT_SYNC_LAG_BLOCKS" | "OPERATIONS_ALERT_WALLET_GRACE_MINUTES" | "OPERATIONS_ALERT_PROOF_BACKLOG" | "OPERATIONS_ALERT_PROOF_BACKLOG_AGE_MINUTES" | "OPERATIONS_ALERT_SPONSOR_BACKLOG" | "OPERATIONS_ALERT_SPONSOR_BACKLOG_AGE_MINUTES" | "OPERATIONS_ALERT_PROOF_RATE_LIMIT_EVENTS" | "OPERATIONS_ALERT_REMINDER_MINUTES" | "PUBLIC_MIDNIGHT_NETWORK" | "PUBLIC_SENSOR_REGISTRY_CONTRACT_ADDRESS">> {}
}
