/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: 07be8246439610261b15124f7cad3dad)
interface __BaseEnv_Env {
	SPONSOR_STATE: R2Bucket;
	DB: D1Database;
	PROOF_QUEUE: Queue;
	SPONSOR_QUEUE: Queue;
	AUTH_RATE_LIMITER: RateLimit;
	API_RATE_LIMITER: RateLimit;
	PROOF_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	PUBLIC_MIDNIGHT_NETWORK: string;
	PUBLIC_SENSOR_REGISTRY_CONTRACT_ADDRESS: string;
	PROOF_SERVER: DurableObjectNamespace<import("./index").ProofServerContainer>;
	SPONSOR_WALLET: DurableObjectNamespace<import("./index").SponsorWalletContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ProofServerContainer" | "SponsorWalletContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_MIDNIGHT_NETWORK" | "PUBLIC_SENSOR_REGISTRY_CONTRACT_ADDRESS">> {}
}
