/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=../deployment/wrangler.verification-mcp.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: d00822f32d9e5987214538c9f18316b8)
interface __BaseEnv_Env {
	VERIFY_RATE_LIMITER: RateLimit;
	ALLOWED_SENSOR_REGISTRY_CONTRACTS: "48636e2f7ae8b1705134b026ec0d5a910357cac990a60adce2c2672e1a78a732";
	PUBLIC_MIDNIGHT_NETWORK: string;
	PUBLIC_SENSOR_REGISTRY_CONTRACT_ADDRESS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_SENSOR_REGISTRY_CONTRACTS" | "PUBLIC_MIDNIGHT_NETWORK" | "PUBLIC_SENSOR_REGISTRY_CONTRACT_ADDRESS">> {}
}
