/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: 6f07f667ba313435d0ab3dad1b960828)
interface __BaseEnv_Env {
	DB: D1Database;
	PROOF_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	INGEST_API_TOKEN: string;
	ATTESTATION_API_TOKEN: string;
	PROOF_SERVER: DurableObjectNamespace<import("./index").ProofServerContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ProofServerContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INGEST_API_TOKEN" | "ATTESTATION_API_TOKEN">> {}
}
