/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=../deployment/wrangler.support-mcp.jsonc --include-runtime=false src/worker-configuration.d.ts` (hash: 3acbedc8e03006f6bac811589694a299)
interface __BaseEnv_Env {
	DB: D1Database;
	SUPPORT_MCP_HOST: "midnight-support-mcp.commun-official.workers.dev";
	CLOUDFLARE_ACCESS_TEAM_DOMAIN: "https://morning-unit-c72e.cloudflareaccess.com";
	CLOUDFLARE_ACCESS_AUDIENCE: "0bcc33f975316e67ad924c2ba21479fab65e827acedebb95a687efa453c207ab";
	PUBLIC_MIDNIGHT_NETWORK: string;
	PUBLIC_SENSOR_REGISTRY_CONTRACT_ADDRESS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPPORT_MCP_HOST" | "CLOUDFLARE_ACCESS_TEAM_DOMAIN" | "CLOUDFLARE_ACCESS_AUDIENCE" | "PUBLIC_MIDNIGHT_NETWORK" | "PUBLIC_SENSOR_REGISTRY_CONTRACT_ADDRESS">> {}
}
